services:
  database:
    image: "postgres:16.0"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - "POSTGRES_DB=study"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=pass"


  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:latest
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: study
      DB_PORT: 5432
      DB_DATABASE: study
      DB_USER: user
      DB_PASSWORD: pass
    ports:
      - "9090:8080"
    depends_on:
      - "database"

  #backend:
  #  build: .
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - "database"

  study-ui:
    image: study-ui
    container_name: study-ui
    build:
      context: ./study-ui
    ports:
      - "4200:80"
  #  depends_on:
  #    - "backend"


